In [4]:
import pandas as pd
import numpy as np
print("My YuvaIntern Data Science Project" )
print("Python is working successfully")

My YuvaIntern Data Science Project
Python is working successfully

In [5]:


import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
print("First 5 rows:")
display(df.head())
print("Dataset shape (rows, columns):", df.shape)
print("\nDataset information:")
df.info()
print("\nMissing values:")
print(df.isnull().sum())

First 5 rows:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Dataset shape (rows, columns): (891, 15)

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

Missing values:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary = missing_summary[missing_summary["Missing Count"] > 0]
missing_summary = missing_summary.sort_values(
    by="Missing Count", ascending=False
)
print("Missing Values Summary:")
display(missing_summary.round(2))
print("Duplicate rows:", df.duplicated().sum())
print("\nData types:")
print(df.dtypes)
print("\nUnique values in categorical columns:")
for col in df.select_dtypes(include="object").columns:
    print(col, ":", df[col].nunique())
print("\nNumerical Summary:")
display(df.describe().round(2))

In [7]:

df_clean = df.copy()
print("Missing values BEFORE cleaning:")
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])
df_clean["age"] = df_clean["age"].fillna(
    df_clean.groupby(["pclass", "sex"])["age"]
    .transform("median")
)
df_clean["age"] = df_clean["age"].fillna(df_clean["age"].median())
df_clean["embarked"] = df_clean["embarked"].fillna(
    df_clean["embarked"].mode()[0]
)
df_clean["embark_town"] = df_clean["embark_town"].fillna(
    df_clean["embark_town"].mode()[0]
)
df_clean = df_clean.drop(columns=["deck"])
print("\nMissing values AFTER cleaning:")
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

print("\nOriginal dataset shape:", df.shape)
print("Cleaned dataset shape:", df_clean.shape)

print("\nFirst five cleaned rows:")
display(df_clean.head())

Missing values BEFORE cleaning:
age            177
embarked         2
deck           688
embark_town      2
dtype: int64

Missing values AFTER cleaning:
Series([], dtype: int64)

Original dataset shape: (891, 15)
Cleaned dataset shape: (891, 14)

First five cleaned rows:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [15]:

rint("Duplicate rows in original dataset:", df.duplicated().sum())
print("Duplicate rows in cleaned dataset:", df_clean.duplicated().sum())
duplicates = df_clean[df_clean.duplicated(keep=False)]
print("\nRows involved in duplication:")
display(duplicates.head(10))

Duplicate rows in original dataset: 107
Duplicate rows in cleaned dataset: 118

Rows involved in duplication:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
26,0,3,male,25.0,0,0,7.2250,C,Third,man,True,Cherbourg,no,True
28,1,3,female,21.5,0,0,7.8792,Q,Third,woman,False,Queenstown,yes,True
29,0,3,male,25.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,Cherbourg,no,True
32,1,3,female,21.5,0,0,7.7500,Q,Third,woman,False,Queenstown,yes,True
37,0,3,male,21.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
42,0,3,male,25.0,0,0,7.8958,C,Third,man,True,Cherbourg,no,True
45,0,3,male,25.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
46,0,3,male,25.0,1,0,15.5000,Q,Third,man,True,Queenstown,no,False

In [16]:
numeric_columns = ["age", "fare", "sibsp", "parch"]
outlier_results = []
for col in numeric_columns:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    count = ((df_clean[col] < lower_limit) |(df_clean[col] > upper_limit)).sum()

    outlier_results.append({"Column": col,"Lower Limit": lower_limit,"Upper Limit": upper_limit,"Potential Outliers": count})

outlier_summary = pd.DataFrame(outlier_results)

display(outlier_summary.round(2))

  Column  Lower Limit  Upper Limit  Potential Outliers
0    age        -0.25        57.75                  33
1   fare       -26.72        65.63                 116
2  sibsp        -1.50         2.50                  46
3  parch         0.00         0.00                 213

In [17]:
df_clean.to_csv("titanic_cleaned.csv", index=False)
print("Cleaned dataset saved successfully!")
print("Final rows and columns:", df_clean.shape)
print("Remaining missing values:", df_clean.isnull().sum().sum())

Cleaned dataset saved successfully!
Final rows and columns: (891, 14)
Remaining missing values: 0